/**
 * generated by Xtext 2.33.0
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Characteristic Basis</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getCharacteristicBasis()
 * @model
 * @generated
 */
public interface CharacteristicBasis extends PredicateTerm
{
} // CharacteristicBasis
