/**
 * generated by Xtext 2.33.0
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumeration Type Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getEnumerationTypeReference()
 * @model
 * @generated
 */
public interface EnumerationTypeReference extends EObject
{
} // EnumerationTypeReference
