/**
 * generated by Xtext 2.33.0
 * Copyright (c) 2022 - 2024 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.query;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unqualified Projected Characteristic Reference Or Alias</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.uddl.query.query.QueryPackage#getUnqualifiedProjectedCharacteristicReferenceOrAlias()
 * @model
 * @generated
 */
public interface UnqualifiedProjectedCharacteristicReferenceOrAlias extends ProjectedCharacteristicReference
{
} // UnqualifiedProjectedCharacteristicReferenceOrAlias
