/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class QueryWebModule extends AbstractQueryWebModule {
}
