/*
 * generated by Xtext 2.33.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.uddl.query.web;

import com.epistimis.uddl.query.QueryRuntimeModule;
import com.epistimis.uddl.query.QueryStandaloneSetup;
import com.epistimis.uddl.query.ide.QueryIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class QueryWebSetup extends QueryStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new QueryRuntimeModule(), new QueryIdeModule(), new QueryWebModule()));
	}
	
}
