name: Build and Upload JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Upload JAR to GitHub Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.repository.releases.latest.upload_url }}
        asset_path: ./target/your-artifact.jar
        asset_name: your-artifact.jar
        asset_content_type: application/java-archive

